sudo: required

language: python

services: 
  - docker

before_install:
  - docker pull jvlythical/kodrive-test:master

script:
  - docker run jvlythical/kodrive-test:master


############################################
# Unstable testing manually, osx env hangs #
############################################
#
# os:
#   - linux
#   - osx
#
# language: python
#
# python:
#   - "2.7"
#   - "pypy"
#
# install:
#   - pip install virtualenv
#   - pip install tox
#   - curl https://raw.githubusercontent.com/Jvlythical/KodeDrive/master/static/get-kdr.py | python
#   - export PATH="$HOME/.local/bin:$PATH"
#
# script:
#   - tox -e py27
